
CREATE TABLE arw_patient (
  research_patient_id VARCHAR(50),
  gender CHAR(1),
  birthdate DATE,
  birthdate_estimated BOOLEAN,
  country VARCHAR(50),
  state_province VARCHAR(255),
  county_district VARCHAR(255),
  city_village VARCHAR(255),
  postal_code VARCHAR(50),
  address1 VARCHAR(255),
  address2 VARCHAR(255),
  address3 VARCHAR(255),
  address4 VARCHAR(255),
  address5 VARCHAR(255),
  address6 VARCHAR(255),
  latitude VARCHAR(50),
  longitude VARCHAR(50),
  dead BOOLEAN,
  death_date DATE,
  age_years_at_death INT,
  age_months_at_death INT,
  cause_of_death VARCHAR(255),
  health_center VARCHAR(255),
  date_created DATE
);