CREATE TABLE mw_asthma_followup (
  asthma_followup_visit_id 		int NOT NULL AUTO_INCREMENT,
  patient_id 				int NOT NULL,
  visit_date 				date DEFAULT NULL,
  location 				varchar(255) DEFAULT NULL,
  planned_visit 			varchar(255) DEFAULT NULL,
  height 				int DEFAULT NULL,
  weight 				int DEFAULT NULL,
  day_symptoms 			int DEFAULT NULL,
  night_symptoms 			int DEFAULT NULL,
  inhaler_use_frequency_daily 	int DEFAULT NULL,
  inhaler_use_frequency_weekly 	int DEFAULT NULL,
  inhaler_use_frequency_monthly 	int DEFAULT NULL,
  inhaler_use_frequency_yearly 	int DEFAULT NULL,
  steroid_inhaler_daily 		varchar(255) DEFAULT NULL,
  number_of_cigarettes_per_day 	int DEFAULT NULL,
  passive_smoking 			varchar(255) DEFAULT NULL,
  cooking_indoor 			varchar(255) DEFAULT NULL,
  exacerbation_today 			varchar(255) DEFAULT NULL,
  asthma_severity 			varchar(255) DEFAULT NULL,
  copd 				varchar(255) DEFAULT NULL,
  other_diagnosis 			varchar(255) DEFAULT NULL,
  treatment_inhaled_b_agonist 	varchar(255) DEFAULT NULL,
  treatment_inhaled_steriod 		varchar(255) DEFAULT NULL,
  treatment_oral_steroid 		varchar(255) DEFAULT NULL,
  treatment_other 			varchar(255) DEFAULT NULL,
  comments 				varchar(255) DEFAULT NULL,
  PRIMARY KEY (asthma_followup_visit_id)
);
