
CREATE TABLE mw_art_initial (
  art_initial_visit_id 			INT NOT NULL AUTO_INCREMENT,
  patient_id    				INT NOT NULL,
  visit_date            			DATE,
  location              			VARCHAR(255),
  who_clinical_conditions 			VARCHAR(255),
  clinical_stage 				VARCHAR(255),
  presumed_hiv_severe_present			VARCHAR(255),
  tb_status 					VARCHAR(255),
  cd4_count					INT,
  cd4_percentage				DECIMAL(6,2),
  ks_side_effects_worsening_on_arvs  		VARCHAR(255),
  cd4_date					DATE,
  pregnant_or_lactating			VARCHAR(255),
  height					DECIMAL(10,2),
  weight					DECIMAL(10,2),
  ever_taken_arvs				VARCHAR(255),
  age_at_initiation				INT,
  last_arvs_taken				VARCHAR(255),
  last_arvs_taken_date				VARCHAR(255),
  confirmatory_test_location   		VARCHAR(255),
  confirmatory_test_date			DATE,
  confirmatory_test_type 			VARCHAR(255),
  art_education_done				VARCHAR(255),
  art_education_date				DATE,
  tb_registration_number			VARCHAR(255),
  tb_treatment_start_date			DATE,
  art_first_line_regimen			VARCHAR(255),
  art_first_line_regimen_start_date		DATE,
  art_alternative_first_line_regimen		VARCHAR(255),
  art_alternative_first_line_regimen_date	DATE,
  art_second_line_regimen			VARCHAR(255),
  art_second_line_regimen_start_date		DATE,
  transfer_in_date				DATE,
  child_hcc_no					VARCHAR(255),
     PRIMARY KEY (art_initial_visit_id)
);
