
CREATE TABLE mw_art_followup (
  art_followup_visit_id 			INT NOT NULL AUTO_INCREMENT,
  patient_id    				INT NOT NULL,
  visit_date            			DATE,
  location              			VARCHAR(255),
  next_appointment_date 			DATE,
  art_drugs_received 				VARCHAR(255),
  pregnant_or_lactating			VARCHAR(255),
  tb_status 					VARCHAR(255),
  doses_missed					DECIMAL(10,2),
  pill_count					INT,
  no_side_effect				VARCHAR(255),
  peripheral_neuropathy_side_effect		VARCHAR(255),
  hepatitis_side_effect			VARCHAR(255),
  skin_rash_side_effect			VARCHAR(255),
  lipodystrophy_side_effect			VARCHAR(255),
  other_side_effect				VARCHAR(255),
  art_regimen					VARCHAR(255),
  height					DECIMAL(10,2),
  weight					DECIMAL(10,2),
  arvs_given					INT,
  arvs_given_to				VARCHAR(255),
  hiv_preventive_therapy			VARCHAR(255),
  therapy_pills		     		DECIMAL(10,2),
  depo_given					VARCHAR(255),
  systolic_bp		 			VARCHAR(255),
  diastolic_bp					VARCHAR(255),
  condoms_given				VARCHAR(255),
     PRIMARY KEY (art_followup_visit_id)
);
