CREATE TABLE mw_ckd_initial (
  ckd_initial_visit_id int NOT NULL AUTO_INCREMENT,
  patient_id int NOT NULL,
  visit_date date DEFAULT NULL,
  location varchar(255) DEFAULT NULL,
  presumed_etiology_hypertension varchar(255) DEFAULT NULL,
  presumed_etiology_diabetes varchar(255) DEFAULT NULL,
  presumed_etiology_hiv varchar(255) DEFAULT NULL,
  presumed_etiology_nephrotic varchar(255) DEFAULT NULL,
  presumed_etiology_drugs varchar(255) DEFAULT NULL,
  presumed_etiology_other varchar(255) DEFAULT NULL,
  presumed_etiology_other_2 varchar(255) DEFAULT NULL,
  presumed_etiology_unknown varchar(255) DEFAULT NULL,
  presumed_etiology_diagnosis_date date DEFAULT NULL,
  diagnosis_chf varchar(255) DEFAULT NULL,
  diagnosis_date_chf date DEFAULT NULL,
  diagnosis_hypertension varchar(255) DEFAULT NULL,
  diagnosis_date_hypertension date DEFAULT NULL,
  diagnosis_diabetes varchar(255) DEFAULT NULL,
  diagnosis_date_diabetes date DEFAULT NULL,
  diagnosis_other varchar(255) DEFAULT NULL,
  diagnosis_date_other date DEFAULT NULL,
  hiv_status varchar(255) DEFAULT NULL,
  hiv_test_date date DEFAULT NULL,
  art_start_date date DEFAULT NULL,
  tb_status varchar(255) DEFAULT NULL,
  tb_date date DEFAULT NULL,
  history_of_dialysis varchar(255) DEFAULT NULL,
  date_of_dialysis date DEFAULT NULL,
  PRIMARY KEY (ckd_initial_visit_id)
);
