CREATE TABLE mw_ckd_followup (
  ckd_followup_visit_id 	int NOT NULL AUTO_INCREMENT,
  patient_id 			int NOT NULL,
  visit_date 			date DEFAULT NULL,
  location 			varchar(255) DEFAULT NULL,
  height 			int DEFAULT NULL,
  weight 			int DEFAULT NULL,
  bp_systolic 			int DEFAULT NULL,
  bp_diastolic 		int DEFAULT NULL,
  heart_rate 			int DEFAULT NULL,
  creatinine 			int DEFAULT NULL,
  gfr 				int DEFAULT NULL,
  urine_protein 		varchar(255) DEFAULT NULL,
  confusion 			varchar(255) DEFAULT NULL,
  fatigue 			varchar(255) DEFAULT NULL,
  nausea 			varchar(255) DEFAULT NULL,
  anorexia 			varchar(255) DEFAULT NULL,
  pruritus 			varchar(255) DEFAULT NULL,
  conjunctiva			varchar(255) DEFAULT NULL,
  ascites 			varchar(255) DEFAULT NULL,
  oedema 			varchar(255) DEFAULT NULL,
  other_symptoms 		varchar(255) DEFAULT NULL,
  ckd_stage 			varchar(255) DEFAULT NULL,
  nsaid_use 			varchar(255) DEFAULT NULL,
  alcohol 			varchar(255) DEFAULT NULL,
  tobacco 			varchar(255) DEFAULT NULL,
  diuretic_hctz 		varchar(255) DEFAULT NULL,
  diuretic_furo 		varchar(255) DEFAULT NULL,
  diuretic_spiro 		varchar(255) DEFAULT NULL,
  ace_i_enal 			varchar(255) DEFAULT NULL,
  ace_i_capt 			varchar(255) DEFAULT NULL,
  ace_i_lisin 			varchar(255) DEFAULT NULL,
  bb_aten 			varchar(255) DEFAULT NULL,
  bb_bis 			varchar(255) DEFAULT NULL,
  bb_prop 			varchar(255) DEFAULT NULL,
  ccb_aml 			varchar(255) DEFAULT NULL,
  ccb_nif 			varchar(255) DEFAULT NULL,
  other_medications 		varchar(255) DEFAULT NULL,
  took_medications_today 	varchar(255) DEFAULT NULL,
  diet_recommendations 	varchar(255) DEFAULT NULL,
  next_appointment_date	date DEFAULT NULL,
  PRIMARY KEY (ckd_followup_visit_id)
);

