
CREATE TABLE mw_diabetes_hypertension_initial (
  initial_visit_id 				INT NOT NULL AUTO_INCREMENT,
  patient_id    				INT NOT NULL,
  visit_date            			DATE,
  location              			VARCHAR(255),
  diagnosis_type_1_diabetes 			VARCHAR(255),
  diagnosis_type_1_diabetes_date		DATE, 
  diagnosis_type_2_diabetes 			VARCHAR(255),
  diagnosis_type_2_diabetes_date		DATE, 
  diagnosis_hypertension 			VARCHAR(255),
  diagnosis_hypertension_date			DATE, 
  hiv_status		 			VARCHAR(255),
  hiv_test_date				DATE, 
  art_start_date				DATE, 
  cardiovascular_disease			VARCHAR(255),
  cardiovascular_disease_date			DATE,
  retinopathy					VARCHAR(255),
  retinopathy_date				DATE,
  renal_disease				VARCHAR(255),
  renal_disease_date				DATE,
  family_history_diabetes_mellitus		VARCHAR(255),
  family_history_hypertension   		VARCHAR(255),
  tb_status					VARCHAR(255),
  tb_status_year		   		VARCHAR(255),
  stroke_and_tia				VARCHAR(255),
  stroke_and_tia_date				DATE,
  peripheral_vascular_disease			VARCHAR(255),
  peripheral_vascular_disease_date		DATE,
  neuropathy					VARCHAR(255),
  neuropathy_date				DATE,
  sexual_disorder				VARCHAR(255),
  sexual_disorder_date				DATE,
     PRIMARY KEY (initial_visit_id)
);
