
CREATE TABLE mw_diabetes_hypertension_followup (
  followup_visit_id 						INT NOT NULL AUTO_INCREMENT,
  patient_id    						INT NOT NULL,
  visit_date            					DATE,
  location              					VARCHAR(255),
  height							DECIMAL(10,2),
  weight							DECIMAL(10,2),
  body_mass_index 						VARCHAR(255),
  bp_stystolic							INT,
  bp_diastolic 						INT,
  pulse_rate							INT,
  hba1c							DECIMAL(10,2),
  fasting_blood_sugar						DECIMAL(10,2),
  blood_sugar_test_type					VARCHAR(255),
  tobbacco							VARCHAR(255),
  alcohol							VARCHAR(255),
  number_of_fruit_and_vegetable_portions			VARCHAR(255),
  days_per_week_with_30_min_of_exercise			INT,
  cardiovascular_risk						VARCHAR(255),
  visual_acuity						VARCHAR(255),
  neuropathy_or_pvd						VARCHAR(255),
  deformities							VARCHAR(255),
  ulcers					     		VARCHAR(255),
  hospitalized_since_last_visit				VARCHAR(255),
  diabetes_med_long_acting		 			VARCHAR(255),
  diabetes_med_short_acting		 			VARCHAR(255),
  diabetes_med_metformin		 			VARCHAR(255),
  diabetes_med_gilbenclamide		 			VARCHAR(255),
  diuretic_hctz			 			VARCHAR(255),
  diuretic_furp			 			VARCHAR(255),
  diuretic_spiro			 			VARCHAR(255),
  ccb_aml				 			VARCHAR(255),
  ccb_nif				 			VARCHAR(255),
  ace_i_enal				 			VARCHAR(255),
  ace_i_capt				 			VARCHAR(255),
  ace_i_lisin			 				VARCHAR(255),
  bb_aten				 			VARCHAR(255),
  bb_bis				 			VARCHAR(255),
  bb_prop				 			VARCHAR(255),
  asprin_asa				 			VARCHAR(255),
  statin_simva			 				VARCHAR(255),
  statin_prava				 			VARCHAR(255),
  statin_atorva			 			VARCHAR(255),
  other_hyd				 			VARCHAR(255),
  other_issmn				 			VARCHAR(255),
  next_appointment_date 					DATE,
     PRIMARY KEY (followup_visit_id)
);
