CREATE TABLE mw_ncd_other_followup (
  ncd_other_followup_visit_id int NOT NULL AUTO_INCREMENT,
  patient_id int NOT NULL,
  visit_date date DEFAULT NULL,
  location varchar(255) DEFAULT NULL,
  height int DEFAULT NULL,
  weight int DEFAULT NULL,
  weight_change varchar(255) DEFAULT NULL,
  bp_systolic int DEFAULT NULL,
  bp_diastolic int DEFAULT NULL,
  heart_rate int DEFAULT NULL,
  spo2 int DEFAULT NULL,
  alcohol varchar(255) DEFAULT NULL,
  tobacco varchar(255) DEFAULT NULL,
  fruit_and_vegetable_portions int DEFAULT NULL,
  days_per_week_exercise int DEFAULT NULL,
  hospitalized_since_last_visit_for_ncd varchar(255) DEFAULT NULL,
  medications varchar(255) DEFAULT NULL,
  medications_changed varchar(255) DEFAULT NULL,
  comments varchar(2000) DEFAULT NULL,
  next_appointment_date date DEFAULT NULL,
  next_appointment_location varchar(255) DEFAULT NULL,
  PRIMARY KEY (ncd_other_followup_visit_id)
);
