CREATE TABLE mw_ncd_other_initial (
  ncd_other_initial_visit_id int NOT NULL AUTO_INCREMENT,
  patient_id int NOT NULL,
  visit_date date DEFAULT NULL,
  location varchar(255) DEFAULT NULL,
  diagnosis_rheumatoid_arthritis varchar(255) DEFAULT NULL,
  diagnosis_date_rheumatoid_arthritis date DEFAULT NULL,
  diagnosis_cirrhosis varchar(255) DEFAULT NULL,
  diagnosis_date_cirrhosis date DEFAULT NULL,
  diagnosis_dvt_or_pe varchar(255) DEFAULT NULL,
  diagnosis_date_dvt_or_pe date DEFAULT NULL,
  diagnosis_sickle_cell_disease varchar(255) DEFAULT NULL,
  diagnosis_other varchar(255) DEFAULT NULL,
  diagnosis_date_other date DEFAULT NULL,
  hiv_status varchar(255) DEFAULT NULL,
  hiv_test_date date DEFAULT NULL,
  art_start_date date DEFAULT NULL,
  tb_status varchar(255) DEFAULT NULL,
  tb_start_date date DEFAULT NULL,
  comorbidities_hypertension varchar(255) DEFAULT NULL,
  comorbidities_diabetes varchar(255) DEFAULT NULL,
  comorbidities_chronic_kidney_disease varchar(255) DEFAULT NULL,
  comorbidities_other varchar(255) DEFAULT NULL,
  echo_test_result varchar(255) DEFAULT NULL,
  echo_test_date date DEFAULT NULL,
  ecg_test_result varchar(255) DEFAULT NULL,
  ecg_test_date date DEFAULT NULL,
  PRIMARY KEY (ncd_other_initial_visit_id)
);

